import React, { useState, useEffect } from 'react';
import {
  Bell,
  FileText,
  ShieldAlert,
  CheckCircle2,
  Clock,
  MapPin,
  AlertTriangle,
  RefreshCw,
  Filter,
  Search,
  Check,
  X
} from 'lucide-react';

export default function AdminAlertsReportsView({ onUpdateData }) {
  const [activeTab, setActiveTab] = useState('reports'); // 'reports' or 'alerts'
  const [alerts, setAlerts] = useState([]);
  const [incidents, setIncidents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all'); // 'all', 'unverified', 'verified'
  const [selectedIncident, setSelectedIncident] = useState(null);
  const [verifyNotes, setVerifyNotes] = useState('');
  const [verifySeverity, setVerifySeverity] = useState('Moderate');
  const [showVerifyModal, setShowVerifyModal] = useState(false);

  const fetchData = async (isInitial = false) => {
    try {
      if (isInitial) setLoading(true);
      const [alertsRes, sitRes] = await Promise.all([
        fetch('http://localhost:8000/api/alerts'),
        fetch('http://localhost:8000/api/field/situational')
      ]);

      if (alertsRes.ok) {
        const alertData = await alertsRes.json();
        setAlerts(prev => JSON.stringify(prev) !== JSON.stringify(alertData || []) ? (alertData || []) : prev);
      }

      if (sitRes.ok) {
        const sitData = await sitRes.json();
        setIncidents(prev => JSON.stringify(prev) !== JSON.stringify(sitData.incidents || []) ? (sitData.incidents || []) : prev);
      }
      if (onUpdateData) onUpdateData();
    } catch (err) {
      console.error('Error fetching alerts & reports:', err);
    } finally {
      if (isInitial) setLoading(false);
    }
  };

  useEffect(() => {
    fetchData(true);
    const intervalId = setInterval(() => fetchData(false), 5000);
    return () => clearInterval(intervalId);
  }, []);

  const handleVerifySubmit = async () => {
    if (!selectedIncident) return;
    try {
      await fetch(`http://localhost:8000/api/field/incidents/${selectedIncident.id}/verify`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ notes: verifyNotes, severity: verifySeverity })
      });
      setShowVerifyModal(false);
      setVerifyNotes('');
      setSelectedIncident(null);
      fetchData();
    } catch (e) {
      console.error('Error verifying incident:', e);
    }
  };

  const unverifiedIncidents = incidents.filter(i => i.status === 'Unverified');
  const verifiedIncidents = incidents.filter(i => i.status === 'Verified');

  const filteredIncidents = incidents.filter(inc => {
    const matchesStatus =
      statusFilter === 'all' ? true :
      statusFilter === 'unverified' ? inc.status === 'Unverified' :
      inc.status === 'Verified';

    const matchesSearch =
      (inc.category || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      (inc.description || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      (inc.location_name || '').toLowerCase().includes(searchQuery.toLowerCase());

    return matchesStatus && matchesSearch;
  });

  const filteredAlerts = alerts.filter(a =>
    (a.message || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
    (a.severity || '').toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div style={{
      height: '100%',
      width: '100%',
      backgroundColor: '#F7F9FB',
      overflowY: 'auto',
      padding: '24px',
      boxSizing: 'border-box'
    }}>
      {/* Page Header */}
      <div style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px'
      }}>
        <div>
          <h1 style={{
            fontSize: '22px',
            fontWeight: 800,
            color: '#0F2747',
            margin: 0,
            display: 'flex',
            alignItems: 'center',
            gap: '10px'
          }}>
            <Bell size={24} color="#2563A8" />
            Alerts & Field User Reports Center
          </h1>
          <p style={{ margin: '4px 0 0 0', color: '#596577', fontSize: '13px' }}>
            Monitor dynamic hazard alerts generated by risk models and review field reports submitted by citizens & NDRF officers.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
          <button
            onClick={fetchData}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              fontSize: '13px',
              padding: '8px 14px',
              borderRadius: '4px',
              border: '1px solid #CBD2DB',
              backgroundColor: '#FFFFFF',
              color: '#263247',
              fontWeight: 600,
              cursor: 'pointer'
            }}
          >
            <RefreshCw size={14} className={loading ? 'spin' : ''} />
            Refresh Telemetry
          </button>
        </div>
      </div>

      {/* KPI Overview Strip - Unified Strip with Dividers (DESIGN.md Section 10 & 14) */}
      <div style={{
        backgroundColor: '#FFFFFF',
        borderRadius: '0px',
        border: '1px solid #E2E7ED',
        padding: '16px 20px',
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        marginBottom: '24px'
      }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', paddingRight: '16px', borderRight: '1px solid #E2E7ED' }}>
          <AlertTriangle size={18} color="#C92A2A" style={{ marginTop: '2px', flexShrink: 0 }} />
          <div>
            <div style={{ fontSize: '11px', fontWeight: 700, color: '#727E8F', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Pending Unverified Reports
            </div>
            <div style={{ fontSize: '24px', fontWeight: 800, color: '#C92A2A', marginTop: '2px' }}>
              {unverifiedIncidents.length} Reports
            </div>
            <div style={{ fontSize: '12px', color: '#596577', marginTop: '2px' }}>
              Requires NDRF ground inspection & confirmation
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', paddingLeft: '16px', paddingRight: '16px', borderRight: '1px solid #E2E7ED' }}>
          <CheckCircle2 size={18} color="#159447" style={{ marginTop: '2px', flexShrink: 0 }} />
          <div>
            <div style={{ fontSize: '11px', fontWeight: 700, color: '#727E8F', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Verified Ground Incidents
            </div>
            <div style={{ fontSize: '24px', fontWeight: 800, color: '#159447', marginTop: '2px' }}>
              {verifiedIncidents.length} Confirmed
            </div>
            <div style={{ fontSize: '12px', color: '#596577', marginTop: '2px' }}>
              Audited & integrated into SDMA response grid
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', paddingLeft: '16px' }}>
          <ShieldAlert size={18} color="#E57A17" style={{ marginTop: '2px', flexShrink: 0 }} />
          <div>
            <div style={{ fontSize: '11px', fontWeight: 700, color: '#727E8F', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Active Model Hazards
            </div>
            <div style={{ fontSize: '24px', fontWeight: 800, color: '#0F2747', marginTop: '2px' }}>
              {alerts.length} Trigger Alerts
            </div>
            <div style={{ fontSize: '12px', color: '#596577', marginTop: '2px' }}>
              Auto-triggered by NASA rain & DEM slope threshold
            </div>
          </div>
        </div>
      </div>

      {/* Tabs & Search Filter Header */}
      <div style={{
        backgroundColor: '#FFFFFF',
        borderRadius: '0px',
        border: '1px solid #E2E7ED',
        padding: '16px 20px',
        marginBottom: '20px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '16px'
      }}>
        {/* Navigation Tabs */}
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            onClick={() => setActiveTab('reports')}
            style={{
              padding: '10px 18px',
              borderRadius: '0px',
              border: 'none',
              backgroundColor: activeTab === 'reports' ? '#0F2747' : '#F0F3F6',
              color: activeTab === 'reports' ? '#FFFFFF' : '#3B4759',
              fontWeight: 700,
              fontSize: '13px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}
          >
            <FileText size={16} color={activeTab === 'reports' ? '#20A18F' : '#727E8F'} />
            User & Citizen Reports
            {unverifiedIncidents.length > 0 && (
              <span style={{
                backgroundColor: '#C92A2A',
                color: '#FFFFFF',
                fontSize: '11px',
                fontWeight: 800,
                borderRadius: '0px',
                padding: '2px 8px',
              }}>
                {unverifiedIncidents.length} Pending
              </span>
            )}
          </button>

          <button
            onClick={() => setActiveTab('alerts')}
            style={{
              padding: '10px 18px',
              borderRadius: '0px',
              border: 'none',
              backgroundColor: activeTab === 'alerts' ? '#0F2747' : '#F0F3F6',
              color: activeTab === 'alerts' ? '#FFFFFF' : '#3B4759',
              fontWeight: 700,
              fontSize: '13px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}
          >
            <Bell size={16} color={activeTab === 'alerts' ? '#E57A17' : '#727E8F'} />
            Model Trigger Alerts ({alerts.length})
          </button>
        </div>

        {/* Search & Filter Bar */}
        <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
          <div style={{ position: 'relative', width: '260px' }}>
            <Search size={16} color="#727E8F" style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)' }} />
            <input
              type="text"
              placeholder="Search reports or alerts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                width: '100%',
                padding: '8px 12px 8px 36px',
                borderRadius: '4px',
                border: '1px solid #CBD2DB',
                fontSize: '13px',
                boxSizing: 'border-box'
              }}
            />
          </div>

          {activeTab === 'reports' && (
            <div style={{ display: 'flex', gap: '6px' }}>
              <button
                onClick={() => setStatusFilter('all')}
                style={{
                  padding: '6px 12px',
                  borderRadius: '4px',
                  border: '1px solid #CBD2DB',
                  backgroundColor: statusFilter === 'all' ? '#2563A8' : '#FFFFFF',
                  color: statusFilter === 'all' ? '#FFFFFF' : '#3B4759',
                  fontSize: '12px',
                  fontWeight: 600,
                  cursor: 'pointer'
                }}
              >
                All ({incidents.length})
              </button>
              <button
                onClick={() => setStatusFilter('unverified')}
                style={{
                  padding: '6px 12px',
                  borderRadius: '4px',
                  border: '1px solid #CBD2DB',
                  backgroundColor: statusFilter === 'unverified' ? '#C92A2A' : '#FFFFFF',
                  color: statusFilter === 'unverified' ? '#FFFFFF' : '#3B4759',
                  fontSize: '12px',
                  fontWeight: 600,
                  cursor: 'pointer'
                }}
              >
                Unverified ({unverifiedIncidents.length})
              </button>
              <button
                onClick={() => setStatusFilter('verified')}
                style={{
                  padding: '6px 12px',
                  borderRadius: '4px',
                  border: '1px solid #CBD2DB',
                  backgroundColor: statusFilter === 'verified' ? '#159447' : '#FFFFFF',
                  color: statusFilter === 'verified' ? '#FFFFFF' : '#3B4759',
                  fontSize: '12px',
                  fontWeight: 600,
                  cursor: 'pointer'
                }}
              >
                Verified ({verifiedIncidents.length})
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Main Content Card Container */}
      <div style={{
        backgroundColor: '#FFFFFF',
        borderRadius: '0px',
        border: '1px solid #E2E7ED',
        padding: '20px'
      }}>
        {activeTab === 'reports' ? (
          filteredIncidents.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px 0', color: '#727E8F', fontSize: '14px' }}>
              No user or citizen reports found matching the criteria.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {filteredIncidents.map((inc) => (
                <div key={inc.id} style={{
                  backgroundColor: inc.status === 'Unverified' ? '#FBE1E1' : '#F7F9FB',
                  border: `1px solid ${inc.status === 'Unverified' ? '#C92A2A' : '#E2E7ED'}`,
                  borderRadius: '0px',
                  padding: '16px',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center'
                }}>
                  <div style={{ flex: 1, paddingRight: '20px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
                      <span style={{
                        fontSize: '11px',
                        fontWeight: 800,
                        padding: '3px 8px',
                        borderRadius: '4px',
                        backgroundColor: inc.status === 'Unverified' ? '#C92A2A' : '#159447',
                        color: '#FFFFFF',
                        textTransform: 'uppercase'
                      }}>
                        {inc.status}
                      </span>
                      <span style={{
                        fontSize: '11px',
                        fontWeight: 700,
                        padding: '3px 8px',
                        borderRadius: '4px',
                        backgroundColor: (inc.risk_level === 'High' || inc.risk_level === 'Critical') ? '#FCE8D3' : '#FFF3D9',
                        color: (inc.risk_level === 'High' || inc.risk_level === 'Critical') ? '#E57A17' : '#D9A441'
                      }}>
                        {inc.risk_level || 'High'} RISK
                      </span>
                      <span style={{ fontSize: '13px', fontWeight: 700, color: '#0F2747' }}>
                        {inc.category}
                      </span>
                    </div>

                    <p style={{ fontSize: '13px', color: '#263247', margin: '4px 0 8px 0', lineHeight: '1.4' }}>
                      {inc.description}
                    </p>

                    <div style={{ display: 'flex', gap: '16px', fontSize: '12px', color: '#727E8F' }}>
                      <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <MapPin size={13} color="#2563A8" />
                        Location: {inc.location_name || `${inc.lat?.toFixed(3)}°N, ${inc.lon?.toFixed(3)}°E`}
                      </span>
                      <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <Clock size={13} />
                        Reported ID: #{inc.id}
                      </span>
                    </div>
                  </div>

                  <div>
                    {inc.status === 'Unverified' ? (
                      <button
                        onClick={() => {
                          setSelectedIncident(inc);
                          setShowVerifyModal(true);
                        }}
                        style={{
                          backgroundColor: '#2563A8',
                          color: '#FFFFFF',
                          border: 'none',
                          borderRadius: '4px',
                          padding: '8px 16px',
                          fontSize: '12px',
                          fontWeight: 700,
                          cursor: 'pointer',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '6px'
                        }}
                      >
                        <Check size={14} />
                        Verify Report
                      </button>
                    ) : (
                      <span style={{ fontSize: '12px', fontWeight: 700, color: '#159447', display: 'flex', alignItems: 'center', gap: '4px' }}>
                        <CheckCircle2 size={16} />
                        Verified Ground Status
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )
        ) : (
          filteredAlerts.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '40px 0', color: '#727E8F', fontSize: '14px' }}>
              No automated model trigger alerts active.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {filteredAlerts.map((alert) => (
                <div key={alert.id} style={{
                  backgroundColor: '#FBE1E1',
                  border: '1px solid #C92A2A',
                  borderRadius: '0px',
                  padding: '16px'
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span style={{ fontSize: '11px', fontWeight: 800, color: '#C92A2A', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                      MODEL TRIGGER ALERT • {alert.severity} RISK
                    </span>
                    <span style={{ fontSize: '11px', color: '#596577', display: 'flex', alignItems: 'center', gap: '4px' }}>
                      <Clock size={13} />
                      {new Date(alert.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>

                  <div style={{ fontSize: '14px', fontWeight: 700, color: '#0F2747', marginBottom: '6px' }}>
                    {alert.message}
                  </div>

                  <div style={{ fontSize: '12px', color: '#596577', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <MapPin size={13} color="#C92A2A" />
                    Target Coordinates: {alert.latitude.toFixed(4)}°N, {alert.longitude.toFixed(4)}°E
                  </div>
                </div>
              ))}
            </div>
          )
        )}
      </div>

      {/* Incident Ground Verification Modal Overlay */}
      {showVerifyModal && selectedIncident && (
        <div style={{
          position: 'fixed',
          top: 0, left: 0, right: 0, bottom: 0,
          backgroundColor: 'rgba(11, 18, 32, 0.65)',
          backdropFilter: 'blur(3px)',
          zIndex: 9999,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}>
          <div style={{
            backgroundColor: '#FFFFFF',
            borderRadius: '0px',
            width: '460px',
            maxWidth: '90%',
            overflow: 'hidden',
          }}>
            <div style={{
              backgroundColor: '#0F2747',
              color: '#FFFFFF',
              padding: '16px 20px',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}>
              <h3 style={{ fontSize: '16px', fontWeight: 700, margin: 0 }}>Ground Incident Verification</h3>
              <button onClick={() => setShowVerifyModal(false)} style={{ background: 'none', border: 'none', color: '#CBD2DB', cursor: 'pointer' }}>
                <X size={18} />
              </button>
            </div>

            <div style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <div style={{ backgroundColor: '#F7F9FB', padding: '12px', borderRadius: '0px', border: '1px solid #E2E7ED' }}>
                <div style={{ fontSize: '11px', fontWeight: 700, color: '#727E8F', textTransform: 'uppercase' }}>REPORT DETAILS</div>
                <div style={{ fontSize: '14px', fontWeight: 700, color: '#0F2747', marginTop: '2px' }}>{selectedIncident.category}</div>
                <p style={{ fontSize: '12px', color: '#3B4759', margin: '4px 0 0 0' }}>{selectedIncident.description}</p>
              </div>

              <div>
                <label style={{ fontSize: '12px', fontWeight: 700, color: '#3B4759', display: 'block', marginBottom: '6px' }}>
                  Confirmed Ground Severity
                </label>
                <select
                  value={verifySeverity}
                  onChange={(e) => setVerifySeverity(e.target.value)}
                  style={{ width: '100%', padding: '10px', borderRadius: '4px', border: '1px solid #CBD2DB', fontSize: '13px' }}
                >
                  <option value="Low">Low Risk - Monitored Slope</option>
                  <option value="Moderate">Moderate Risk - Road Debris / Partial Blockage</option>
                  <option value="High">High Risk - Active Slope Failure / Highway Closure</option>
                  <option value="Critical">Critical - Life Safety Hazard / Emergency Evacuation</option>
                </select>
              </div>

              <div>
                <label style={{ fontSize: '12px', fontWeight: 700, color: '#3B4759', display: 'block', marginBottom: '6px' }}>
                  Field Officer Verification Notes
                </label>
                <textarea
                  rows={3}
                  placeholder="Record NDRF unit inspection notes..."
                  value={verifyNotes}
                  onChange={(e) => setVerifyNotes(e.target.value)}
                  style={{ width: '100%', padding: '10px', borderRadius: '4px', border: '1px solid #CBD2DB', fontSize: '13px', fontFamily: 'inherit' }}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '8px' }}>
                <button
                  type="button"
                  onClick={() => setShowVerifyModal(false)}
                  style={{ padding: '8px 14px', borderRadius: '4px', border: '1px solid #CBD2DB', backgroundColor: '#FFFFFF', fontSize: '13px', fontWeight: 600, cursor: 'pointer' }}
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleVerifySubmit}
                  style={{ padding: '8px 16px', borderRadius: '4px', border: 'none', backgroundColor: '#159447', color: '#FFFFFF', fontSize: '13px', fontWeight: 700, cursor: 'pointer' }}
                >
                  Confirm & Verify Report
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
